version = 0.1

[default.deploy.parameters]
stack_name = "AsmblyFacilitiesMaintTrackingStack"
resolve_s3 = true
s3_prefix = "AsmblyFacilitiesMaintTrackingStack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
