AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: >
  A collection of Lambda functions for Asmbly automation tasks,
  organized by job type.

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
  NeonSecretName:
    Type: String
    Description: The name of the AWS Secrets Manager secret containing NeonCRM credentials.
    Default: "prod/neon_token"

  AsmblyHostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /config/route53/asmbly/hosted-zone-id
    Description: The Route 53 Hosted Zone ID for asmbly.org. Fetched from SSM Parameter Store.

Conditions:
  IsProd: !Equals [!Ref Stage, 'prod']

Resources:
  FacilitiesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        openapi: '3.0.1'
        info:
          title: !Sub 'Asmbly Facilities API - ${Stage}'
          version: '1.0'
        paths:
          /SlackSlashReorder:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PurchaseRequestStack.Outputs.SlackSlashReorderFunctionArn}/invocations"
              responses: {}
          /KilnOpsDropoffRecentEntriesViewer:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CeramicsStack.Outputs.KilnDropoffViewerFunctionArn}/invocations"
              responses: {}

          /purchase-request/new:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PurchaseRequestStack.Outputs.NewPurchaseRequestReceivedFunctionArn}/invocations"
              responses: {}

          /purchase-request/slack-reaction:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PurchaseRequestStack.Outputs.PurchaseRequestReactionFunctionArn}/invocations"
              responses: {}
          /problem-report/slack-reaction:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProblemReportStack.Outputs.ProblemReportReactionFunctionArn}/invocations"
              responses: {}
          /slack/events:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RoutersStack.Outputs.SlackEventSubscriptionsRouterFunctionArn}/invocations"
              responses: {}

          /waiver/new:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AdministrativeStack.Outputs.NewWaiverCompletedFunctionArn}/invocations"
              responses: {}
  RequestsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "requests-layer-${Stage}"
      Description: "Shared layer containing the requests library"
      ContentUri: layers/requests_layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "common-layer-${Stage}"
      Description: "Shared layer for common utilities (aws, clickup, slack)"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  ReactionMapPurchaseRequestParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/config/reaction-handler/purchase-request"
      Type: String
      Description: "JSON mapping of reactions to statuses for purchase requests. This parameter is created and managed by the root template.yaml."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ./configs/reactions_purchase_request.json
      Tags:
        Project: slack-reaction-purchase-request
        Workspace: facilities
        Stage: !Ref Stage

  ReactionMapProblemReportParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/config/reaction-handler/problem-report"
      Type: String
      Description: "JSON mapping of reactions to statuses for problem reports. This parameter is created and managed by the root template.yaml."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ./configs/reactions_problem_report.json
      Tags:
        Project: slack-reaction-problem-report
        Workspace: facilities
        Stage: !Ref Stage

  RouterConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/config/router/slack-event-router"
      Type: String
      Description: "JSON configuration for the Slack event router, including channel IDs. This parameter is created and managed by the root template.yaml."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ./configs/router_config.json
      Tags:
        Project: facilities-slack-event-router
        Workspace: facilities
        Stage: !Ref Stage

  ClickUpWorkspaceFieldIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/config/clickup/field/workspace"
      Type: String
      Description: "JSON configuration for ClickUp, including the workspace field ID. This parameter is created and managed by the root template.yaml."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ./configs/clickup_field_workspace.json
      Tags:
        Project: facilities-clickup-config
        Workspace: facilities
        Stage: !Ref Stage

  FacilitiesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/facilities.yaml
      Parameters:
        Stage: !Ref Stage
        ClickUpWorkspaceFieldIdParameterName: !Ref ClickUpWorkspaceFieldIdParameter
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  PurchaseRequestStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/purchase_request.yaml
      Parameters:
        Stage: !Ref Stage
        ClickUpWorkspaceFieldIdParameterName: !Ref ClickUpWorkspaceFieldIdParameter
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  CeramicsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/ceramics.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  ProblemReportStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/problem_report.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  RoutersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/routers.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        PurchaseRequestReactionFunctionArn: !GetAtt PurchaseRequestStack.Outputs.PurchaseRequestReactionFunctionArn
        ProblemReportReactionFunctionArn: !GetAtt ProblemReportStack.Outputs.ProblemReportReactionFunctionArn
        RouterConfigParameterName: !Ref RouterConfigParameter

  AdministrativeStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/administrative.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer
        NeonSecretName: !Ref NeonSecretName
  PurchaseRequestInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PurchaseRequestStack.Outputs.SlackSlashReorderFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  PurchaseRequestReactionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PurchaseRequestStack.Outputs.PurchaseRequestReactionFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  NewPurchaseRequestInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PurchaseRequestStack.Outputs.NewPurchaseRequestReceivedFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  ProblemReportReactionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ProblemReportStack.Outputs.ProblemReportReactionFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  CeramicsInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CeramicsStack.Outputs.KilnDropoffViewerFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  SlackEventRouterInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RoutersStack.Outputs.SlackEventSubscriptionsRouterFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  NewWaiverCompletedInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AdministrativeStack.Outputs.NewWaiverCompletedFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  # --- Custom Domain Infrastructure (PROD-ONLY) ---
  # These resources are only created when the Stage parameter is 'prod'

  FacilitiesCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsProd
    Properties:
      DomainName: facilities.asmbly.org
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: facilities.asmbly.org
          HostedZoneId: !Ref AsmblyHostedZoneId # Fetched from SSM
      Tags:
        - Key: Project
          Value: facilities-api
        - Key: Workspace
          Value: facilities

  FacilitiesApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: IsProd
    Properties:
      DomainName: facilities.asmbly.org
      DomainNameConfigurations:
        - CertificateArn: !Ref FacilitiesCertificate
          EndpointType: REGIONAL
      Tags:
        Project: facilities-api
        Workspace: facilities
    DependsOn:
      - FacilitiesCertificate

  FacilitiesApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: IsProd
    Properties:
      DomainName: !Ref FacilitiesApiCustomDomain
      ApiId: !Ref FacilitiesApi
      Stage: !Ref Stage # This will be 'prod' when IsProd is true
    DependsOn:
      - FacilitiesApiCustomDomain

  FacilitiesDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsProd
    Properties:
      HostedZoneId: !Ref AsmblyHostedZoneId # Fetched from SSM
      Name: facilities.asmbly.org
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt FacilitiesApiCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt FacilitiesApiCustomDomain.RegionalDomainName
    DependsOn:
      - FacilitiesApiCustomDomain

Outputs:
  FacilitiesApiUrl:
    Description: "The invoke URL for the Facilities API Gateway"
    Value: !Sub "https://{FacilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"

  FacilitiesProdUrl:
    Description: "The custom, friendly URL for the PROD API Gateway"
    Condition: IsProd # This output is only created for 'prod'
    Value: "https://facilities.asmbly.org"