# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: >
  A collection of Lambda functions for Asmbly automation tasks,
  organized by job type.

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  # 1. Define the API Gateway for the new reorder functions
  FacilitiesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  # 2. Define the Shared Lambda Layer
  RequestsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "requests-layer-${Stage}"
      Description: "Shared layer containing the requests library"
      ContentUri: layers/requests_layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "common-layer-${Stage}"
      Description: "Shared layer for common utilities (aws, clickup, slack)"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  FacilitiesResources:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ./templates/facilities.yaml
  
  PurchaseRequestResources:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ./templates/purchase_request.yaml
  
  CeramicsResources:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ./templates/ceramics.yaml
  
  ProblemReportResources:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ./templates/problem_report.yaml

# Add this entire section to the end of your file
Outputs:
  FacilitiesApiUrl:
    Description: "The invoke URL for the Facilities API Gateway"
    Value: !Sub "https://${FacilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
