AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: >
  A collection of Lambda functions for Asmbly automation tasks,
  organized by job type.

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  # 1. Define the API Gateway and its explicit routes
  FacilitiesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        openapi: '3.0.1'
        info:
          title: 'Asmbly Facilities API'
          version: '1.0'
        paths:
          /FacilitiesSlackPurchaseReorder:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PurchaseRequestStack.Outputs.PurchaseReorderFunction}/invocations"
              responses: {}
          /KilnOpsDropoffRecentEntriesViewer:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST # Note: This must be POST for Lambda proxy integrations
                type: aws_proxy
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CeramicsStack.Outputs.KilnDropoffViewerFunction}/invocations"
              responses: {}

  # 2. Define the Shared Lambda Layers
  RequestsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "requests-layer-${Stage}"
      Description: "Shared layer containing the requests library"
      ContentUri: layers/requests_layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "common-layer-${Stage}"
      Description: "Shared layer for common utilities (aws, clickup, slack)"
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  # 3. Define the Nested Application Stacks
  FacilitiesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/facilities.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  PurchaseRequestStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/purchase_request.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer
        FacilitiesApiId: !Ref FacilitiesApi # <-- This was the missing line

  CeramicsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/ceramics.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer
        FacilitiesApiId: !Ref FacilitiesApi # <-- This was the missing line

  ProblemReportStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/problem_report.yaml
      Parameters:
        Stage: !Ref Stage
        CommonLayerARN: !Ref CommonLayer
        RequestsLayerARN: !Ref RequestsLambdaLayer

  # 4. Grant API Gateway permission to invoke the Lambda functions
  PurchaseRequestInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PurchaseRequestStack.Outputs.PurchaseReorderFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

  CeramicsInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CeramicsStack.Outputs.KilnDropoffViewerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FacilitiesApi}/*/*"

Outputs:
  FacilitiesApiUrl:
    Description: "The invoke URL for the Facilities API Gateway"
    Value: !Sub "https://${FacilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"