AWSTemplateFormatVersion: '2010-09-09'
Description: Resources for Ceramics-focused Lambda functions.

Resources:
  # --- Ceramics: Kiln Dropoff Viewer ---
  KilnDropoffViewerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "KilnDropoffViewerLambdaRole-${Stage}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: KilnDropoffViewerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:clickup/api/token-*'
      Tags:
        - Key: Project
          Value: kilnops-dropoff-viewer
        - Key: Workspace
          Value: ceramics

  KilnDropoffRecentEntriesViewerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KilnOpsDropoffRecentEntriesViewer-${Stage}"
      Description: "Generates a public-facing HTML page showing recent kiln drop-off submissions from ClickUp for the last 24 hours. Triggered by API Gateway."
      CodeUri: ../functions/ceramics/kiln_dropoff_recent_entries_viewer/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Role: !GetAtt KilnDropoffViewerLambdaRole.Arn
      Layers:
        - !Ref RequestsLambdaLayer
        - !Ref CommonLayer
      Environment:
        Variables:
          SECRET_NAME: clickup/api/token
          CLICKUP_LIST_KILNDROP_ID: 901318902829
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /KilnOpsDropoffRecentEntriesViewer
            Method: get
            RestApiId: !Ref FacilitiesApi
      Tags:
        Project: kilnops-dropoff-viewer
        Workspace: ceramics