AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for Ceramics-focused Lambda functions.

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
  RequestsLayerARN:
    Type: String
    Description: The ARN of the shared Requests Lambda Layer.
  CommonLayerARN:
    Type: String
    Description: The ARN of the shared Common Utilities Lambda Layer.

Resources:
  KilnDropoffViewerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "KilnDropoffViewerLambdaRole-${Stage}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: KilnDropoffViewerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:clickup/api/token-*'
      Tags:
        - Key: Project
          Value: kilnops-dropoff-viewer
        - Key: Workspace
          Value: ceramics

  KilnDropoffRecentEntriesViewerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KilnOpsDropoffRecentEntriesViewer-${Stage}"
      Description: "Generates a public-facing HTML page showing recent kiln drop-off submissions."
      CodeUri: ../functions/ceramics/kiln_dropoff_recent_entries_viewer/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Role: !GetAtt KilnDropoffViewerLambdaRole.Arn
      Layers:
        - !Ref RequestsLayerARN
        - !Ref CommonLayerARN
      Environment:
        Variables:
          SECRET_NAME: 'clickup/api/token'
          CLICKUP_LIST_KILNDROP_ID: 901318902829
      Tags:
        Project: kilnops-dropoff-viewer
        Workspace: ceramics

Outputs:
  KilnDropoffViewerFunctionArn:
    Description: "The ARN of the Kiln Dropoff Viewer Lambda Function"
    Value: !GetAtt KilnDropoffRecentEntriesViewerFunction.Arn