AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for Problem Report-focused Lambda functions.

# Parameters are required because the root template passes them in
Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
  RequestsLayerARN:
    Type: String
    Description: The ARN of the shared Requests Lambda Layer.
  CommonLayerARN:
    Type: String
    Description: The ARN of the shared Common Utilities Lambda Layer.

Resources:
  # This is a harmless placeholder to make the template valid
  Placeholder:
    Type: AWS::CloudFormation::WaitConditionHandle