AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: Resources for Purchase Request-focused Lambda functions.

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (e.g., dev, stage, prod).
  RequestsLayerARN:
    Type: String
    Description: The ARN of the shared Requests Lambda Layer.
  CommonLayerARN:
    Type: String
    Description: The ARN of the shared Common Utilities Lambda Layer.
  ClickUpWorkspaceFieldIdParameterName:
    Type: String

Resources:
  ClickUpMasterItemsListParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/clickup/facilities/masterItemsList"
      Type: String
      Description: "JSON configuration for the ClickUp Master Items List ID."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ../configs/clickup_facilities_masterItemsList.json
      Tags:
        Project: slack-slash-reorder
        Workspace: facilities
        Stage: !Ref Stage

  ClickUpPurchaseRequestsConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/clickup/facilities/purchaseRequests"
      Type: String
      Description: "JSON configuration for the ClickUp Purchase Requests list and its custom field IDs."
      Value:
        Fn::ToJsonString:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: ../configs/clickup_facilities_purchaseRequests.json
      Tags:
        Project: purchase-requests
        Workspace: facilities
        Stage: !Ref Stage

  SlackReorderStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "SlackReorderStateTable-${Stage}"
      AttributeDefinitions:
        - AttributeName: view_id
          AttributeType: S
      KeySchema:
        - AttributeName: view_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: slack-slash-reorder
        - Key: Workspace
          Value: facilities
        - Key: Stage
          Value: !Ref Stage

  SlackSlashReorderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "SlackSlashReorderFunction-${Stage}"
      Description: "Handles a Slack slash command to create a reorder/purchase request in ClickUp."
      CodeUri: ../functions/purchase_request/slack_slash_reorder/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 10
      Layers:
        - !Ref RequestsLayerARN
        - !Ref CommonLayerARN
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SlackSlashReorderFunction-${Stage}'
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackReorderStateTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref ClickUpWorkspaceFieldIdParameterName
        - SSMParameterReadPolicy:
            ParameterName: !GetAtt ClickUpMasterItemsListParameter.Name
        - SSMParameterReadPolicy:
            ParameterName: !GetAtt ClickUpPurchaseRequestsConfigParameter.Name
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:clickup/api/token-*'
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:slack-maintenancebot-token-*'
      Environment:
        Variables:
          STATE_TABLE_NAME: !Ref SlackReorderStateTable
          CLICKUP_SECRET_NAME: 'clickup/api/token'
          SLACK_MAINTENANCE_BOT_SECRET_NAME: !Sub 'slack-maintenancebot-token'
          CLICKUP_MASTER_ITEMS_LIST_CONFIG_PARAM_NAME: !Ref ClickUpMasterItemsListParameter
          CLICKUP_PURCHASE_REQUESTS_CONFIG_PARAM_NAME: !Ref ClickUpPurchaseRequestsConfigParameter
          CLICKUP_WORKSPACE_FIELD_ID_PARAM_NAME: !Ref ClickUpWorkspaceFieldIdParameterName
      Tags:
        Project: slack-slash-reorder
        Workspace: facilities
        Stage: !Ref Stage

  PurchaseRequestReactionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: [sts:AssumeRole]
      Policies:
        - PolicyName: PurchaseRequestReactionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:clickup/api/token-*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:slack-maintenancebot-token-*'
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/config/reaction-handler/purchase-request'
      Tags:
        - Key: Project
          Value: slack-reaction-purchase-request
        - Key: Workspace
          Value: facilities
        - Key: Stage
          Value: !Ref Stage

  PurchaseRequestReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "PurchaseRequest-ReactionFunction-${Stage}"
      Description: "Handles a Slack reaction webhook to update a ClickUp task status."
      CodeUri: ../functions/purchase_request/slack_reaction_webhook/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 10
      Role: !GetAtt PurchaseRequestReactionRole.Arn
      Layers:
        - !Ref RequestsLayerARN
        - !Ref CommonLayerARN
      Environment:
        Variables:
          REACTION_MAP_PARAMETER_NAME: !Sub "/${Stage}/config/reaction-handler/purchase-request"
          SLACK_MAINTENANCE_BOT_SECRET_NAME: 'slack-maintenancebot-token'
          CLICKUP_SECRET_NAME: 'clickup/api/token'
      Tags:
        Project: slack-reaction-purchase-request
        Workspace: facilities
        Stage: !Ref Stage

  NewPurchaseRequestReceivedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: [sts:AssumeRole]
      Policies:
        - PolicyName: NewPurchaseRequestReceivedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:clickup/api/token-*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:slack-maintenancebot-token-*'
              - Effect: Allow
                Action: ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ClickUpWorkspaceFieldIdParameterName}'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/clickup/facilities/purchaseRequests'
      Tags:
        - Key: Project
          Value: new-purchase-request-received
        - Key: Workspace
          Value: facilities
        - Key: Stage
          Value: !Ref Stage

  NewPurchaseRequestReceivedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "NewPurchaseRequestReceivedFunction-${Stage}"
      Description: "Handles a ClickUp webhook for new purchase requests, posts to Slack, and updates the task."
      CodeUri: ../functions/purchase_request/new_purchase_request_received/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt NewPurchaseRequestReceivedRole.Arn
      Layers:
        - !Ref RequestsLayerARN
        - !Ref CommonLayerARN
      Environment:
        Variables:
          CLICKUP_SECRET_NAME: 'clickup/api/token'
          SLACK_MAINTENANCE_BOT_SECRET_NAME: 'slack-maintenancebot-token'
          SLACK_CHANNEL_ID: 'C026YVA7TK3' # <-- Replace with your actual channel ID
          SLACK_BOT_NAME: 'Purchase Bot'
          SLACK_BOT_EMOJI: ':moneybag:'
          SLACK_WORKSPACE_URL: 'https://asmbly-makerspace.slack.com'
          CLICKUP_WORKSPACE_FIELD_ID_PARAM_NAME: !Ref ClickUpWorkspaceFieldIdParameterName
          CLICKUP_PURCHASE_REQUESTS_CONFIG_PARAM_NAME: !Ref ClickUpPurchaseRequestsConfigParameter
      Tags:
        Project: new-purchase-request-received
        Workspace: facilities
        Stage: !Ref Stage

Outputs:
  SlackSlashReorderFunctionArn:
    Description: "The ARN of the Slack Slash Reorder Lambda Function"
    Value: !GetAtt SlackSlashReorderFunction.Arn
  PurchaseRequestReactionFunctionArn:
    Description: "The ARN of the Slack Reaction Webhook Lambda Function"
    Value: !GetAtt PurchaseRequestReactionFunction.Arn
  NewPurchaseRequestReceivedFunctionArn:
    Description: "The ARN of the New Purchase Request Received Lambda Function"
    Value: !GetAtt NewPurchaseRequestReceivedFunction.Arn